---
- name:     add extra packages
  yum:      name={{ item }} state=present
  with_items:
    - epel-release

- name:     install packages
  yum:      name={{ item }} state=present
  with_items:
    - libselinux-python
    - httpd
    - php
    - phpmyadmin

- name:     httpd service state
  service:  name=httpd state=started enabled=yes

- name:     configure httpd
  template: src=localhost.conf.j2 dest=/etc/httpd/conf.d/localhost.conf
  notify:   restart httpd

- name:     remove phpMyAdmin.conf
  file:     path=/etc/httpd/conf.d/phpMyAdmin.conf state=absent
  notify:   restart httpd
