---
- name:        deploy and configure webservers
  hosts:       webservers
  remote_user: vagrant
  sudo:        yes

  roles:
    - web

- name:        deploy and configure databases
  hosts:       dbservers
  remote_user: vagrant
  sudo:        yes

  roles:
    - db

- name:        deploy and configure wordpress
  hosts:       wpservers
  remote_user: vagrant
  sudo:        yes

  roles:
    - wp
