---
- name:       symlink wordpress
  file:       src=/srv/wordpress dest=/var/www/html state=link force=yes

- name:       create wordpress development folders
  file:       path=/srv/wordpress/wp-content/{{ item }} state=directory
  with_items:
    - themes
    - plugins

- name:       symlink wordpress development folders
  file:       src=/vagrant/wordpress/{{ item }} dest=/srv/wordpress/wp-content/{{ item }} state=link force=yes
  with_items:
    - themes
    - plugins

- name:       download wordpress
  get_url:    url=https://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv

- name:       unarchive wordpress
  unarchive:  src=/srv/wordpress-{{ wp_version }}.tar.gz dest=/srv copy=no

- name:       create mysql database
  mysql_db:   name={{ wp_db_name }} state=present

- name:       import mysql database schema
  mysql_db:   name={{ wp_db_name }} state=import target=/vagrant/{{ wp_db_schema }}

- name:       create database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host=localhost state=present

- name:       create mysql backup script
  template:   src=mysql-backup.sh.j2 dest=~vagrant/mysql-backup.sh mode=0755

- name:       configure wordpress
  template:   src=wp-config-sample.php.j2 dest=/srv/wordpress/wp-config.php

- name:       change ownership of wordpress
  file:       path=/srv/wordpress owner=apache group=apache state=directory recurse=yes
